<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="TestNG"
           tests="2"
           failures="2"
           errors="0"
           skipped="0"
           time="10.609">
  <properties />
            <testcase name="verifySMSDonutValues" time="3.280" classname="com.digi.selenium.app.Dashboard_Prepaid_Stg">
                <failure type="java.lang.AssertionError"
                  message="expected [54.00] but found [0.00]"
              >
<![CDATA[java.lang.AssertionError: expected [54.00] but found [0.00]
  org.testng.Assert.fail(Assert.java:94)
  org.testng.Assert.failNotEquals(Assert.java:496)
  org.testng.Assert.assertEquals(Assert.java:125)
  org.testng.Assert.assertEquals(Assert.java:178)
  org.testng.Assert.assertEquals(Assert.java:188)
  com.digi.selenium.app.Dashboard_Prepaid_Stg.verifySMSDonutValues(Dashboard_Prepaid_Stg.java:235)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:648)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:834)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1142)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
  org.testng.TestRunner.privateRun(TestRunner.java:771)
  org.testng.TestRunner.run(TestRunner.java:621)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
  org.testng.SuiteRunner.run(SuiteRunner.java:259)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1176)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1101)
  org.testng.TestNG.run(TestNG.java:1009)
  org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
  org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
  org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
      </failure>

          </testcase>
            <testcase name="verifyVoiceDonutValues" time="7.329" classname="com.digi.selenium.app.Dashboard_Prepaid_Stg">
                <failure type="java.lang.AssertionError"
                  message="expected [106.00] but found [null]"
              >
<![CDATA[java.lang.AssertionError: expected [106.00] but found [null]
  org.testng.Assert.fail(Assert.java:94)
  org.testng.Assert.failNotEquals(Assert.java:496)
  org.testng.Assert.assertEquals(Assert.java:116)
  org.testng.Assert.assertEquals(Assert.java:178)
  org.testng.Assert.assertEquals(Assert.java:188)
  com.digi.selenium.app.Dashboard_Prepaid_Stg.verifyVoiceDonutValues(Dashboard_Prepaid_Stg.java:98)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:648)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:834)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1142)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
  org.testng.TestRunner.privateRun(TestRunner.java:771)
  org.testng.TestRunner.run(TestRunner.java:621)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
  org.testng.SuiteRunner.run(SuiteRunner.java:259)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1176)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1101)
  org.testng.TestNG.run(TestNG.java:1009)
  org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
  org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
  org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
      </failure>

          </testcase>
  
  
  
</testsuite>
